# Generated by Django 4.2.1 on 2023-10-06 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodRecipeSharingApp', '0002_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FoodRecipeSharingApp.recipe'),
        ),
    ]
