# Generated by Django 4.2.1 on 2023-10-08 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodRecipeSharingApp', '0003_alter_recipeimage_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeimage',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='FoodRecipeSharingApp.recipeimage'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='step_number',
            field=models.IntegerField(unique=True),
        ),
    ]
