# Generated by Django 4.2.1 on 2023-11-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodRecipeSharingApp', '0007_alter_favourite_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipestep',
            name='step_number',
            field=models.IntegerField(),
        ),
    ]
