# Generated by Django 4.2.1 on 2023-12-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodRecipeSharingApp', '0009_favourite_unique_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
