# Generated by Django 4.2.1 on 2024-03-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodRecipeSharingApp', '0010_rating_country'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('recipe', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('recipe', 'user')},
        ),
    ]
